FROM node:24-alpine

COPY . /opt/

WORKDIR /opt

RUN npm build && npm run build

RUN apk updtae && apk add apache2

# DIST/INDEX.HTML --> /VAR/WW/HTML

RUN rm -f /var/www/localhost/htdocs/*
RUN cp -rf dist/* /var/www/localhost/htdocs/

EXPOSE 80

CMD [ "httpd","-D","FOREGROUND" ] 

# entrypoint apachectl , -D , FOREGROUND